project('libctru', ['c', 'cpp'],
    version: '2.7.0',
    license: 'MIT',
    meson_version: '>=1.1.0',
    default_options : ['cpp_std=gnu++11']
)

if get_option('profiling')
    message('Enabling profiling hooks')
    add_project_arguments('-DPROFILING', language: ['c', 'cpp'])
endif

sources = files(
    'libctru/source/3dslink.c',
    'libctru/source/allocator/addrmap.h',
    'libctru/source/allocator/linear.cpp',
    'libctru/source/allocator/mappable.c',
    'libctru/source/allocator/mem_pool.cpp',
    'libctru/source/allocator/mem_pool.h',
    'libctru/source/allocator/vram.cpp',
    'libctru/source/applets/error.c',
    'libctru/source/applets/miiselector.c',
    'libctru/source/applets/swkbd.c',
    'libctru/source/archive_dev.c',
    # 'libctru/source/console.c', # Skip console because we don't need it.
    'libctru/source/env.c',
    'libctru/source/errf.c',
    'libctru/source/font.c',
    'libctru/source/gdbhio.c',
    'libctru/source/gdbhio_dev.c',
    'libctru/source/gfx.c',
    'libctru/source/gpu/gpu.c',
    'libctru/source/gpu/gx.c',
    'libctru/source/gpu/gxqueue.c',
    'libctru/source/gpu/shaderProgram.c',
    'libctru/source/gpu/shbin.c',
    'libctru/source/internal.h',
    'libctru/source/ndsp/ndsp-channel.c',
    'libctru/source/ndsp/ndsp-filter.c',
    'libctru/source/ndsp/ndsp-internal.h',
    'libctru/source/ndsp/ndsp.c',
    'libctru/source/os-versionbin.c',
    'libctru/source/os.c',
    'libctru/source/path_buf.c',
    'libctru/source/path_buf.h',
    'libctru/source/romfs_dev.c',
    'libctru/source/services/ac.c',
    'libctru/source/services/act.c',
    'libctru/source/services/am.c',
    'libctru/source/services/ampxi.c',
    'libctru/source/services/apt.c',
    'libctru/source/services/boss.c',
    'libctru/source/services/cam.c',
    'libctru/source/services/cdcchk.c',
    'libctru/source/services/cfgnor.c',
    'libctru/source/services/cfgu.c',
    'libctru/source/services/csnd.c',
    'libctru/source/services/dsp.c',
    'libctru/source/services/frd.c',
    'libctru/source/services/frdn.c',
    'libctru/source/services/fs.c',
    'libctru/source/services/fspxi.c',
    'libctru/source/services/fsreg.c',
    'libctru/source/services/gspgpu.c',
    'libctru/source/services/gsplcd.c',
    'libctru/source/services/hid.c',
    'libctru/source/services/httpc.c',
    'libctru/source/services/ir.c',
    'libctru/source/services/irrst.c',
    'libctru/source/services/loader.c',
    'libctru/source/services/mcuhwc.c',
    'libctru/source/services/mic.c',
    'libctru/source/services/mvd.c',
    'libctru/source/services/ndm.c',
    'libctru/source/services/news.c',
    'libctru/source/services/nfc.c',
    'libctru/source/services/nim.c',
    'libctru/source/services/ns.c',
    'libctru/source/services/nwmext.c',
    'libctru/source/services/pmapp.c',
    'libctru/source/services/pmdbg.c',
    'libctru/source/services/ps.c',
    'libctru/source/services/ptmgets.c',
    'libctru/source/services/ptmplays.c',
    'libctru/source/services/ptmsets.c',
    'libctru/source/services/ptmsysm.c',
    'libctru/source/services/ptmu.c',
    'libctru/source/services/pxidev.c',
    'libctru/source/services/pxipm.c',
    'libctru/source/services/qtm.c',
    'libctru/source/services/qtmc.c',
    'libctru/source/services/soc/soc_accept.c',
    'libctru/source/services/soc/soc_addglobalsocket.c',
    'libctru/source/services/soc/soc_bind.c',
    'libctru/source/services/soc/soc_closesocket.c',
    'libctru/source/services/soc/soc_closesockets.c',
    'libctru/source/services/soc/soc_common.c',
    'libctru/source/services/soc/soc_common.h',
    'libctru/source/services/soc/soc_connect.c',
    'libctru/source/services/soc/soc_fcntl.c',
    'libctru/source/services/soc/soc_gai_strerror.c',
    'libctru/source/services/soc/soc_getaddrinfo.c',
    'libctru/source/services/soc/soc_gethostbyaddr.c',
    'libctru/source/services/soc/soc_gethostbyname.c',
    'libctru/source/services/soc/soc_gethostid.c',
    'libctru/source/services/soc/soc_gethostname.c',
    'libctru/source/services/soc/soc_getipinfo.c',
    'libctru/source/services/soc/soc_getnameinfo.c',
    'libctru/source/services/soc/soc_getnetworkopt.c',
    'libctru/source/services/soc/soc_getpeername.c',
    'libctru/source/services/soc/soc_getsockname.c',
    'libctru/source/services/soc/soc_getsockopt.c',
    'libctru/source/services/soc/soc_herror.c',
    'libctru/source/services/soc/soc_hstrerror.c',
    'libctru/source/services/soc/soc_inet_addr.c',
    'libctru/source/services/soc/soc_inet_aton.c',
    'libctru/source/services/soc/soc_inet_ntoa.c',
    'libctru/source/services/soc/soc_inet_ntop.c',
    'libctru/source/services/soc/soc_inet_pton.c',
    'libctru/source/services/soc/soc_init.c',
    'libctru/source/services/soc/soc_ioctl.c',
    'libctru/source/services/soc/soc_listen.c',
    'libctru/source/services/soc/soc_poll.c',
    'libctru/source/services/soc/soc_recv.c',
    'libctru/source/services/soc/soc_recvfrom.c',
    'libctru/source/services/soc/soc_select.c',
    'libctru/source/services/soc/soc_send.c',
    'libctru/source/services/soc/soc_sendto.c',
    'libctru/source/services/soc/soc_setsockopt.c',
    'libctru/source/services/soc/soc_shutdown.c',
    'libctru/source/services/soc/soc_shutdownsockets.c',
    'libctru/source/services/soc/soc_sockatmark.c',
    'libctru/source/services/soc/soc_socket.c',
    'libctru/source/services/srvpm.c',
    'libctru/source/services/sslc.c',
    'libctru/source/services/uds.c',
    'libctru/source/services/y2r.c',
    'libctru/source/srv.c',
    'libctru/source/synchronization.c',
    'libctru/source/system/allocateHeaps.c',
    'libctru/source/system/appExit.c',
    'libctru/source/system/appInit.c',
    'libctru/source/system/ctru_exit.c',
    'libctru/source/system/ctru_init.c',
    'libctru/source/system/initArgv.c',
    'libctru/source/system/syscalls.c',
    'libctru/source/thread.c',
    'libctru/source/util/decompress/decompress.c',
    'libctru/source/util/rbtree/rbtree_clear.c',
    'libctru/source/util/rbtree/rbtree_empty.c',
    'libctru/source/util/rbtree/rbtree_find.c',
    'libctru/source/util/rbtree/rbtree_init.c',
    'libctru/source/util/rbtree/rbtree_insert.c',
    'libctru/source/util/rbtree/rbtree_internal.h',
    'libctru/source/util/rbtree/rbtree_iterator.c',
    'libctru/source/util/rbtree/rbtree_minmax.c',
    'libctru/source/util/rbtree/rbtree_remove.c',
    'libctru/source/util/rbtree/rbtree_rotate.c',
    'libctru/source/util/rbtree/rbtree_size.c',
    'libctru/source/util/utf/decode_utf16.c',
    'libctru/source/util/utf/decode_utf8.c',
    'libctru/source/util/utf/encode_utf16.c',
    'libctru/source/util/utf/encode_utf8.c',
    'libctru/source/util/utf/utf16_to_utf32.c',
    'libctru/source/util/utf/utf16_to_utf8.c',
    'libctru/source/util/utf/utf32_to_utf16.c',
    'libctru/source/util/utf/utf32_to_utf8.c',
    'libctru/source/util/utf/utf8_to_utf16.c',
    'libctru/source/util/utf/utf8_to_utf32.c',
)

sources_asm = files(
    'libctru/source/svc.s',
    'libctru/source/system/readtp.s',
    'libctru/source/system/stack_adjust.s',
)

includes = include_directories('libctru/include')

libctru_asm = static_library(
    'ctru_asm',
    sources_asm,
    include_directories: includes,
    c_args: ['-xassembler-with-cpp'],
)

libctru = static_library(
    'ctru',
    sources,
    include_directories: includes,
)

libctru_dep = declare_dependency(
    include_directories: includes,
    link_with: [libctru, libctru_asm],
)
